version: "3.9"

services:
  proxy:
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./proxy/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./proxy/certs:/etc/nginx/certs
    environment:
      - "DOMAIN=${DOMAIN}"
    depends_on:
      - wordpress

  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
      - db
    image: wordpress:php8.0
    volumes:
      - ./:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/conf.d/php.ini
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    extra_hosts:
      - "wpssl.local:${DOCKER_BRIDGE_GATEWAY_IP}" # this has to be the gateway IP of the docker's bridge network

volumes:
  db_data: {}
  wordpress_data: {}
